services:
  client:
    build: ./client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
    environment:
      - NODE_ENV=production
      - CHOKIDAR_USEPOLLING=true
      - NEXT_PUBLIC_API_URL=http://server:8000
    depends_on:
      - server

  server:
    build: ./server
    ports:
      - "8000:8000"
    volumes:
      - ./server:/app
      - sqlite_data:/app/data
    environment:
      - DATABASE_URL=sqlite:///./data/database.db

volumes:
  sqlite_data: